# Generated by Django 5.0.14 on 2025-05-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_no', models.IntegerField()),
                ('device_id', models.CharField(max_length=50)),
                ('total_result', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('assembly_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_type', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=10, null=True)),
                ('work_group', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_description', models.CharField(max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cvqs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='logs.qualitylog')),
            ],
        ),
    ]
